### ISSUE TITLE
Create form for filters on the homepage

### ISSUE THREAD

**Issue by BeaBravo** [nicholascatalano/restaurant-blog#86]
this will go in the <aside> section

**Comment by BeaBravo** [comment]
- [ ] This will go in the homepage.handlebars in the aside section
- [ ] It will grab Price Range, Rating, City, Cuisine and Subcategory from available restaurants
- [ ] Add an 'Apply Filters' button that takes you to another page with the results

**Comment by YuliyaTsoy** [comment]
adds some css
